### ISSUE TITLE
Display waveform for pre-recorded audio file.

### ISSUE THREAD

**Issue by sachi097** [AbreezaSaleem/react-voice-recorder-player#10]
Consider an use-case where the audio file already exist and the user wants to load it to the plugin and display the waveform without actually recording the audio.

Does the plugin already has this feature? If not, it would be great to implement this feature because there might be scenarios where user do not want to record the audio in real-time but display the waveform for pre-recorded audio.

If above said feature is implemented then it makes sense to also implement the onLoad audio event.

**Comment by AbreezaSaleem** [comment]
Hello. This has been implemented in the new release. You can find its details here: https://github.com/AbreezaSaleem/react-voice-recorder-player/releases/tag/v1.2.0
