### ISSUE TITLE
No .d.ts file for typescript configuration

### ISSUE THREAD

**Issue by kbarbry** [AbreezaSaleem/react-voice-recorder-player#11]
I may be doing something wrong but apparently even if on npm it says that this plugin is typecript compatible, when installing it on my project it can't find any .d.ts file and in fact in the node_modules no d.ts files for this plugin.

Maybe someone already did one for this plugin and could make a pr ?

![image](https://github.com/AbreezaSaleem/react-voice-recorder-player/assets/86127065/db887908-430c-4420-bcc3-edbf8e65dfd1)

**Comment by AbreezaSaleem** [comment]
Hello. Thanks for bringing this to my attention. This issue has been fixed in the new release. Details can be found here: https://github.com/AbreezaSaleem/react-voice-recorder-player/releases/tag/v1.2.0
