### ISSUE TITLE
not being able to work with time

### ISSUE THREAD

**Issue by mahdimirmohamadi** [AbreezaSaleem/react-voice-recorder-player#8]
what can we do if we want to execute some functions based on the time passed? 

for example i want to stop recording after 40 seconds and user should not be able to record more than that. 

i didn't see any method or props related to this Time Topic in the docs. 

any help would be appreciated

**Comment by AbreezaSaleem** [comment]
Hi. I'll try to add this functionality in the next couple of weeks. In the meantime you're welcome to open Pull Request containing the requested changes. :)
