### ISSUE TITLE
Add customizability to MediaRecorder options (noiseCancellation, echo, etc.)

### ISSUE THREAD

**Issue by davidchi31415** [AbreezaSaleem/react-voice-recorder-player#9]
More customizability over these options would be nice.

**Comment by AbreezaSaleem** [comment]
Hi. I'll get to this in the next two weeks hopefully. In the meantime you're welcome to open Pull Request containing the requested changes. :)

**Comment by AbreezaSaleem** [comment]
@davidchi31415 So I had a chance to look into this and `MediaDevices` API by default provides us with Noise Suppression and Echo Cancelling. Details about such constraints can be found [here](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints) and I doubt people will want to turn these off.

However, I can take this a step further and do some audio processing to enhance the audio quality. Its a compelling idea and I might look into it but for now I am closing this ticket.
